### ISSUE TITLE
Could you please share the thesis?

### ISSUE THREAD

**Issue by James-Yip** [keithwars/dialogueAutomaticMetrics#1]

**Comment by keithwars** [comment]
This is the link to the condensed article: https://arxiv.org/abs/1910.11790

The full thesis is to be found here: https://drive.google.com/file/d/1cZbUpZy-MgOXqlwlzj1KaZ9-e1So3HPW/view?usp=sharing

**Comment by James-Yip** [comment]
@keithwars Thanks!
